- name: Restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: Reload nftables
  ansible.builtin.command: nft -f /etc/nftables.conf
  changed_when: true

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
